import { chromium } from 'playwright';
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const errs = [], bad = [];
p.on('pageerror', e => errs.push(String(e.message))); p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
p.on('response', r => { if (r.status() >= 400) bad.push(r.status() + ' ' + r.url()); });
await p.goto('https://avoidgame.io/railavoid/', { waitUntil: 'load' });
await p.waitForTimeout(9000);
const r = await p.evaluate(() => ({ url: location.href, ready: !!(window.__RAIL && window.__RAIL.ready), view: !!(window.__RAIL && window.__RAIL.view), phase: window.__RAIL && window.__RAIL.state.phase }));
await p.screenshot({ path: 'verify/screenshots/live_title.png' });
await p.goto('https://avoidgame.io/games/railavoid/'); await p.waitForTimeout(3000);
await p.screenshot({ path: 'verify/screenshots/live_catalog_page.png', fullPage: false });
console.log(JSON.stringify({ ...r, errs: errs.slice(0, 5), bad: bad.slice(0, 5) }));
await b.close();
